#pragma once

#ifndef CONFIG_EXAMPLES_SLAVE_CONTROLLER_MQUEUE_IMU_NAME
#define CONFIG_EXAMPLES_SLAVE_CONTROLLER_MQUEUE_IMU_NAME "/mq_imu"
#endif

#ifndef CONFIG_EXAMPLES_SLAVE_CONTROLLER_MQUEUE_PROXIMITY_SENSOR_NAME
#define CONFIG_EXAMPLES_SLAVE_CONTROLLER_MQUEUE_PROXIMITY_SENSOR_NAME "/mq_proximity"
#endif

#ifndef CONFIG_EXAMPLES_SLAVE_CONTROLLER_MQUEUE_TEMPERATURE_SENSOR_NAME
#define CONFIG_EXAMPLES_SLAVE_CONTROLLER_MQUEUE_TEMPERATURE_SENSOR_NAME "/mq_temperature"
#endif

struct IMUData
{

};

struct ProximitySensorData
{

};

struct TemperatureSensorData
{

};

