#pragma once

#ifndef CONFIG_EXAMPLES_WINCH_CONTROLLER_MQUEUE_NAME
#define CONFIG_EXAMPLES_WINCH_CONTROLLER_MQUEUE_NAME "/mqwinch"
#endif

#ifndef CONFIG_EXAMPLES_WINCH_CONTROLLER_PWM_DEVNAME
#define CONFIG_EXAMPLES_WINCH_CONTROLLER_PWM_DEVNAME "/dev/pwm0"
#endif

#ifndef CONFIG_EXAMPLES_WINCH_CONTROLLER_MAX_REEL_SPEED_PERCENT
#define CONFIG_EXAMPLES_WINCH_CONTROLLER_MAX_REEL_SPEED_PERCENT 100
#endif


