#pragma once

#ifndef CONFIG_EXAMPLES_NUM_LOADCELLS
#define CONFIG_EXAMPLES_NUM_LOADCELLS 2
#endif

#ifndef CONFIG_EXAMPLES_LOADCELL_RATED_KG
#define CONFIG_EXAMPLES_LOADCELL_RATED_KG 100
#endif

#ifndef CONFIG_EXAMPLES_LOADCELL_I2C_FD
#  define CONFIG_EXAMPLES_LOADCELL_I2C_FD "/dev/i2c0"
#endif

#ifndef CONFIG_EXAMPLES_LOADCELL_MUX_SELECT_PIN_BIT_0
#  define CONFIG_EXAMPLES_LOADCELL_MUX_SELECT_PIN_BIT_0 "/dev/gpio0"
#endif

#ifndef CONFIG_EXAMPLES_LOADCELL_MUX_SELECT_PIN_BIT_1
#  define CONFIG_EXAMPLES_LOADCELL_MUX_SELECT_PIN_BIT_1 "/dev/gpio1"
#endif

#ifndef CONFIG_EXAMPLES_LOADCELL_MUX_SELECT_PIN_BIT_2
#  define CONFIG_EXAMPLES_LOADCELL_MUX_SELECT_PIN_BIT_2 "/dev/gpio2"
#endif
