#pragma once



#ifndef CONFIG_EXAMPLES_MASTER_AND_SLAVE_CONTROLLER_MQUEUE_DRONE_TO_STRETCHER_NAME
#define CONFIG_EXAMPLES_MASTER_AND_SLAVE_CONTROLLER_MQUEUE_DRONE_TO_STRETCHER_NAME "/mq_drone_to_stretcher"
#endif

#ifndef CONFIG_EXAMPLES_MASTER_AND_SLAVE_CONTROLLER_MQUEUE_STRETCHER_TO_DRONE_NAME
#define CONFIG_EXAMPLES_MASTER_AND_SLAVE_CONTROLLER_MQUEUE_STRETCHER_TO_DRONE_NAME "/mq_stretcher_to_stretcher"
#endif

#ifndef CONFIG_EXAMPLES_MASTER_CONTROLLER_MQUEUE_DRONE_TO_FLIGHT_CONTROLLER_NAME
#define CONFIG_EXAMPLES_MASTER_CONTROLLER_MQUEUE_DRONE_TO_FLIGHT_CONTROLLER_NAME "/mq_drone_to_flight_controller"
#endif

#ifndef CONFIG_EXAMPLES_MASTER_CONTROLLER_MQUEUE_FLIGHT_CONTROLLER_TO_DRONE_NAME
#define CONFIG_EXAMPLES_MASTER_CONTROLLER_MQUEUE_FLIGHT_CONTROLLER_TO_DRONE_NAME "/mq_flight_controller_to_drone"
#endif

#ifndef CONFIG_EXAMPLES_MASTER_CONTROLLER_MQUEUE_WINCHCONTROL_NAME
#define CONFIG_EXAMPLES_MASTER_CONTROLLER_MQUEUE_WINCHCONTROL_NAME "/mq_winchcontrol"
#endif

#ifndef CONFIG_EXAMPLES_MASTER_CONTROLLER_MQUEUE_LOADCELL_NAME
#define CONFIG_EXAMPLES_MASTER_CONTROLLER_MQUEUE_LOADCELL_NAME "/mq_loadcell"
#endif

#ifndef CONFIG_EXAMPLES_MASTER_CONTROLLER_MQUEUE_OPTICALENCODER_NAME
#define CONFIG_EXAMPLES_MASTER_CONTROLLER_MQUEUE_OPTICALENCODER_NAME "/mq_opticalencoder"
#endif


enum class WinchDirection
{
    DOWN,
    UP
};

struct DroneToStretcherData
{

};

struct StretcherToDroneData
{

};

struct DroneToFlightControllerData
{

};

struct FlightControllerToDroneData
{

};

struct WinchControlData
{
    int new_duty = 0;
    WinchDirection direction = WinchDirection::DOWN;
};

struct LoadCellData
{

};

struct OpticalEncoderData
{
    float length;
    float rpm;
};