#pragma once

#ifndef CONFIG_EXAMPLES_TCP_CONTROLLER_PORT_NUM
#define CONFIG_EXAMPLES_TCP_CONTROLLER_PORT_NUM 5000
#endif

#ifndef CONFIG_EXAMPLES_TCP_CONTROLLER_SERVER_IP
#define CONFIG_EXAMPLES_TCP_CONTROLLER_SERVER_IP "10.0.0.2"
#endif

#ifndef CONFIG_EXAMPLES_TCP_CONTROLLER_CLIENT_IP
#define CONFIG_EXAMPLES_TCP_CONTROLLER_CLIENT_IP "10.0.0.3"
#endif

#ifndef CONFIG_EXAMPLES_TCP_CONTROLLER_IFNAME
#define CONFIG_EXAMPLES_TCP_CONTROLLER_IFNAME "wlan0"
#endif

#ifndef CONFIG_EXAMPLES_TCP_CONTROLLER_SSID
#define CONFIG_EXAMPLES_TCP_CONTROLLER_SSID "MyWiFiNetwork"
#endif

#ifndef CONFIG_EXAMPLES_TCP_CONTROLLER_PASSWORD
#define CONFIG_EXAMPLES_TCP_CONTROLLER_PASSWORD "password123"
#endif

