#pragma once

#ifndef CONFIG_EXAMPLES_TCPCONTROLLER_PORT_NUM
#define CONFIG_EXAMPLES_TCPCONTROLLER_PORT_NUM 5000
#endif

#ifndef CONFIG_EXAMPLES_TCPCONTROLLER_SERVER_IP
#define CONFIG_EXAMPLES_TCPCONTROLLER_SERVER_IP "10.0.0.2"
#endif

#ifndef CONFIG_EXAMPLES_TCPCONTROLLER_CLIENT_IP
#define CONFIG_EXAMPLES_TCPCONTROLLER_CLIENT_IP "10.0.0.3"
#endif

#ifndef CONFIG_EXAMPLES_TCPCONTROLLER_IFNAME
#define CONFIG_EXAMPLES_TCPCONTROLLER_IFNAME "wlan0"
#endif

#ifndef CONFIG_EXAMPLES_TCPCONTROLLER_SSID
#define CONFIG_EXAMPLES_TCPCONTROLLER_SSID "MyWiFiNetwork"
#endif

#ifndef CONFIG_EXAMPLES_TCPCONTROLLER_PASSWORD
#define CONFIG_EXAMPLES_TCPCONTROLLER_PASSWORD "password123"
#endif

