#pragma once

#ifndef CONFIG_EXAMPLES_OPTICALENCODER_GPIOA
#define CONFIG_EXAMPLES_OPTICALENCODER_GPIOA "/dev/gpio4"
#endif

#ifndef CONFIG_EXAMPLES_OPTICALENCODER_GPIOB
#define CONFIG_EXAMPLES_OPTICALENCODER_GPIOB "/dev/gpio3"
#endif

#ifndef CONFIG_EXAMPLES_OPTICALENCODER_PPR
#define CONFIG_EXAMPLES_OPTICALENCODER_PPR 24
#endif

#ifndef CONFIG_EXAMPLES_OPTICALENCODER_SIGNO
#define CONFIG_EXAMPLES_OPTICALENCODER_SIGNO SIGUSR1
#endif

#ifndef CONFIG_EXAMPLES_OPTICALENCODER_INITIAL_LENGTH_METERS
#define CONFIG_EXAMPLES_OPTICALENCODER_INITIAL_LENGTH_METERS 0
#endif

#ifndef CONFIG_EXAMPLES_OPTICALENCODER_AVERAGE_DRUM_RADIUS_CM
#define CONFIG_EXAMPLES_OPTICALENCODER_AVERAGE_DRUM_RADIUS_CM 10
#endif

