#pragma once

#ifndef CONFIG_EXAMPLES_OPTICAL_ENCODER_GPIOA
#define CONFIG_EXAMPLES_OPTICAL_ENCODER_GPIOA "/dev/gpio4"
#endif

#ifndef CONFIG_EXAMPLES_OPTICAL_ENCODER_GPIOB
#define CONFIG_EXAMPLES_OPTICAL_ENCODER_GPIOB "/dev/gpio3"
#endif

#ifndef CONFIG_EXAMPLES_OPTICAL_ENCODER_PPR
#define CONFIG_EXAMPLES_OPTICAL_ENCODER_PPR 24
#endif

#ifndef CONFIG_EXAMPLES_OPTICAL_ENCODER_SIGNO
#define CONFIG_EXAMPLES_OPTICAL_ENCODER_SIGNO SIGUSR1
#endif

#ifndef CONFIG_EXAMPLES_OPTICAL_ENCODER_INITIAL_LENGTH_METERS
#define CONFIG_EXAMPLES_OPTICAL_ENCODER_INITIAL_LENGTH_METERS 0.0
#endif

#ifndef CONFIG_EXAMPLES_OPTICAL_ENCODER_AVERAGE_DRUM_RADIUS_CM
#define CONFIG_EXAMPLES_OPTICAL_ENCODER_AVERAGE_DRUM_RADIUS_CM 10.0
#endif

